[Interface]
Address = 10.24.0.1/24
SaveConfig = false
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 51820
PrivateKey = uCv6qRJle+HdYGBG/ot+3UAySCbQ4HwFBVavwStgvXs=

[Peer]
PublicKey = 4rePf87Pt8B+uywtAnuepnAP2foynykSBMhIKG7+WTU=
AllowedIPs = 10.24.0.2/32

[Peer]
PublicKey = 6NFfO45/cOdItTPLRKPCReWjOFkBzFpm0Nhschc9Uwc=
AllowedIPs = 10.24.0.4/32

[Peer]
PublicKey = co0FAMY1YiIIsJ0h5TFjOUTuAtI87fln8aVqGIEFQ1o=
AllowedIPs = 10.24.0.8/32

[Peer]
PublicKey = T6/X1k6mP4qG0N5ZkF/53o6E1J4C5m5H4N5g7u5H7H8=
AllowedIPs = 10.24.0.9/32

[Peer]
PublicKey = hfPGFz135bYxz9eROoL8nXU7WVZv0PNE6iDl037ztmo=
AllowedIPs = 10.24.0.10/32
Endpoint = 90.210.124.168:43175

[Peer]
PublicKey = N3C79JyZ21rQS6iNKn+rK8gMYQoUQF5aO60EuTGQflE=
AllowedIPs = 10.24.0.11/32
Endpoint = 90.210.124.168:36760

[Peer]
PublicKey = 9HYCu/3SdpVcJoLSNIV46DHH3MFnz1GVw0nyMtV8um8=
AllowedIPs = 10.24.0.12/32
Endpoint = 103.166.245.57:3771

[Peer]
PublicKey = 87aVEgnS4VKpTsod4KdutyVNQGMRY95NfJRdd7CpJkM=
AllowedIPs = 10.24.0.13/32
Endpoint = 223.181.9.237:12620

[Peer]
PublicKey = uiL9NC/kVz9wSnLSurUmMc5S8Yy5p8H3YHC/CDZognU=
AllowedIPs = 10.24.0.5/32
Endpoint = 223.181.9.237:15166
