// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxUvYWd8Gp-s4P1jwHaHXjJPty1dnMqg4',
    appId: '1:371315886913:web:53dd0053302f7993ae2fc0',
    messagingSenderId: '371315886913',
    projectId: 'atmos-vpn',
    authDomain: 'atmos-vpn.firebaseapp.com',
    storageBucket: 'atmos-vpn.firebasestorage.app',
    measurementId: 'G-30LG2B3KGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFMO9wQfgwqN0Sse3russq7-KfB62cSDo',
    appId: '1:371315886913:android:b6d45d42f3510a93ae2fc0',
    messagingSenderId: '371315886913',
    projectId: 'atmos-vpn',
    storageBucket: 'atmos-vpn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0KfniLPuSDrRXWwlaiO-A_kbiuGIOX8U',
    appId: '1:371315886913:ios:e08bd9e2f26958a8ae2fc0',
    messagingSenderId: '371315886913',
    projectId: 'atmos-vpn',
    storageBucket: 'atmos-vpn.firebasestorage.app',
    androidClientId: '371315886913-djsgn7m71ao2tegvcion4c5vra12bbpb.apps.googleusercontent.com',
    iosClientId: '371315886913-gftksk78hcd6r9dlkvba96mjk93d7ng6.apps.googleusercontent.com',
    iosBundleId: 'com.atmosvpn.app',
  );

}